tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"

brew "git"
brew "neovim"
brew "redis"
brew "postgres"
brew "hub"
brew "imagemagick"
brew "node"
brew "z"
brew "visionmedia-watch"
brew "mobile-shell"
brew "nmap"
brew "wget"
brew "pass"
brew "tmux"
brew "gpg"
brew "pinentry-mac"
brew "shpotify"

cask "google-chrome"
cask "spotify"
cask "iterm2-nightly"
cask "slack"
cask "visual-studio-code"
cask "atom"
cask "postman"
cask "postico"
cask "google-backup-and-sync"
cask "qlcolorcode"
cask "qlstephen"
cask "qlmarkdown"
cask "qlprettypatch"
cask "quicklook-json"
cask "quicklook-csv"
cask "suspicious-package"

mas "Lungo", id: 1263070803
mas "Spark", id: 1176895641
