#!/usr/bin/env bash

usage() {
  cat <<-EOF

    Usage: node-app <name> [options]

    Create the following structure for a basic node.js project:

      app/
        css/
          style.styl
        js/
          index.js
      lib/
      test/
      index.js
      Makefile
      package.json
      Readme.md

    In addition, a new Git repo will be initialized.

EOF
exit
}

abort() {
  echo " $@" 1>&2
  exit 1
}

log() {
  echo " ○ $@"
}

application=$1
test -z "$application" && usage

test -d "$application" && abort "$application already exists."

echo "Creating express application '$application'"

mkdir $application
cd $application

# Generate a Makefile
echo '
STYL=$(shell find app/css -name "*.styl")

all: public/build.js public/app.css

server:
	supervisor index.js

ifneq ($(NODE_ENV),development)

public/app.js: $(JS)
	node_modules/.bin/browserify app/js/index.js | node_modules/.bin/uglifyjs > public/app.js

public/app.css: $(STYL)
	node_modules/.bin/stylus --resolve-url --inline --compress --include public --include node_modules/nib/lib < app/css/style.styl > public/app.css

else

public/app.js: $(JS)
	node_modules/.bin/browserify app/js/billings.js > public/build.js

public/app.css: $(STYL)
	node_modules/.bin/stylus --resolve-url --inline --include node_modules/nib/lib < app/css/style.styl > public/app.css

endif

clean:
	rm tmp/* public/app.css public/build.js

.PHONY: server clean
' > Makefile

log created Makefile

# Generate the Readme file
cat << EOF > Readme.md
# $application

## Install
```
$ npm install
$ make
```

## License
MIT

EOF

log created Readme.md

cat << EOF > index.js
var express = require('express');
var cookieParser = require('cookie-parser');
var session = require('express-session');
var bodyParser = require('body-parser');
var app = express();

app.set('port', process.env.PORT || 3000);
app.set('view engine', 'jade');
app.set('views', __dirname + '/views');
app.use(cookieParser());
app.use(session({secret: process.env.SESSION_SECRET || 'Yo'}));
app.use(bodyParser());
app.locals.pretty = true;

if ('development' === app.get('env'))
  app.use(express.static(__dirname + '/public'));

app.get('/', function(req, res) {
  res.send('Hello World');
});

app.use(function(req, res) {
  res.send(404);
});

require('app-listen')(app);

EOF

log created package.json

npm install --save express body-parser mocha browserify uglify-js jade stylus nib app-listen

cat << EOF > .gitignore
.DS_Store
node_modules
dump.rdb
npm-debug.log
EOF

mkdir {test,lib,app}
mkdir app/{css,js}

log created app/
log created test/
log created lib/

touch app/css/style.styl
touch app/js/index.js

npm init
git init > /dev/null
git add .
git commit -a -m "Initial commit" > /dev/null
log initializing git repo

echo "Done."
