#!/usr/bin/env bash

usage() {
  cat <<-EOF

    Usage: node-app <name> [options]

    Create the following structure for a basic node.js project:

      test/
      index.js
      Makefile
      package.json
      Readme.md

    In addition, a new Git repo will be initialized.

    Options:
      --no-git        do not initialize a git repo
      --npm           run npm install

EOF
exit
}

abort() {
  echo " $@" 1>&2
  exit 1
}

log() {
  echo " ○ $@"
}

application=$1
test -z "$application" && usage

test -d "$application" && abort "$application already exists."

echo "Creating application $application"

mkdir $application
cd $application

# Generate a Makefile
cat << EOF > Makefile
install:
  @npm install

test:
  ./node_modules/.bin/mocha --reporter=spec --colors

.PHONY: install test
EOF

log created Makefile

# Generate the Readme file
cat << EOF > Readme.md
# $application

## Usage
```js
```

## License
MIT

EOF

log created Readme.md

cat << EOF > .gitignore
.DS_Store
node_modules
dump.rdb
npm-debug.log
EOF

touch index.js
mkdir test

log created test/

npm init
git init > /dev/null
git add .
git commit -a -m "Initial commit" > /dev/null
log initializing git repo

echo "Done."
